version: "3.9"
services:
  app:
    container_name: myapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules